name: dron_delivery_app
description: A Flutter project for hack.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.5
  freezed_annotation: ^2.4.1
  google_fonts: ^6.1.0
  dio: ^5.3.3
  auto_route: ^7.2.0
  cupertino_icons: ^1.0.6
  json_annotation: ^4.8.1
  pinput: ^3.0.1
  intl: ^0.18.1
  pretty_dio_logger: ^1.3.1
  logger: ^2.0.2
  retrofit: ^4.0.3
  flutter_svg: ^2.0.8
  shared_preferences: ^2.2.2
  uuid: ^3.0.7
  url_launcher: ^6.1.14
  decimal: ^2.3.3
  webview_flutter: ^4.4.1
  dadata_suggestions:
    git:
      url: https://github.com/AurelVU/dadata_suggestions.git
      ref: null_saffety



dev_dependencies:
  flutter_test:
    sdk: flutter

  freezed: ^2.4.5
  json_serializable: ^6.6.1
  retrofit_generator: ^6.0.0+3
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6

flutter:
#  generate: true
  uses-material-design: true

  assets:
    - assets/
